### PR TITLE
Dev_Branch

### PR DESCRIPTION
**Pull request by mitalraithatha**
Task A is ready for review.
Please let's know if any changes are there.

### CODE REVIEW

**Review by navid-hossain — APPROVED** [review]
The folder structure was checked if it was according to the required structure of task A and the makefile was also checked. It is observed that the folder structure is categorized according to the specified structure and the makefile is compiling correctly and generating the executable files.

**Review by tarimislam — APPROVED** [review]
We check everything. It's all right. But output text file is not storing file in exact location after executing.

**Comment by mitalraithatha** [comment]
> We check everything. It's all right. But output text file is not storing file in exact location after executing.

We have checked for the same and its working perfectly with the correct location after executing.we are able to see every time updated output file as the correct location only.
Here i am attaching the snapshot of the output files execution with correct path.

Please look into that and let us know what we have interpreted is correct or not.


verification_2

Task_A_verification

**Comment by tarimislam** [comment]
Everything seems good. Good to go

**Pull request merged**
