### PR TITLE
Dev branch E

### PR DESCRIPTION
**Pull request by mitalraithatha**
We have completed our task E.
Please look into that and review us back.
Thanks.
.
we have created the .cpp file which gives the analytics data at the end, in different average_output.txt file.
The new output file contains :
the Average delay introduced in subnet1 
Average delay introduced in subnet2 
Total number of packets successfully sent for the entire simulation 
Total delay introduced from sender to receiver for 20 data packets.
this function is only works for ABP simulator functionalities as delay's will work or generate in ABP simulator only.

### CODE REVIEW

**Review by tarimislam — CHANGES_REQUESTED** [review]
image
The whole simulation is not running

**Review by navid-hossain — COMMENTED** [review]
Hello, when i ran the simulation, the ouput files formatted_abp_output.txt and average_output.txt files are not updating. If you look at the time the files are generated you can see. please check inot this matter. thanks

**Comment by mitalraithatha** [comment]
Hello reviewers , The issue you raised is resolved.

Actually we were using ECLIPSE IDE software for simulation and running purpose,so in that it was working properly because they are taking the input from the files differently.
.
but as you requested so we have changed input paths according to linux platform and now that is also working perfectly.
.
so please look into this and let us know.
thank you in advance.

**Comment by navid-hossain** [comment]
> Hello reviewers , The issue you raised is resolved.
> 
> Actually we were using ECLIPSE IDE software for simulation and running purpose,so in that it was working properly because they are taking the input from the files differently.
> .
> but as you requested so we have changed input paths according to linux platform and now that is also working perfectly.
> .
> so please look into this and let us know.
> thank you in advance.

We have checked it again. Its working fine now. The output files are updating each time we run the simulation. The only issue is the indentation problem in format_convert.cpp file. Please use 4 spaces instead of tab. If you use tab its showing different here in github. Thanks!

**Review by tarimislam — COMMENTED** [review]
Everything looks except indentation problem

**Comment by mitalraithatha** [comment]
If everything is ok then can you please approve it so we can merge final branch?

**Review by tarimislam — APPROVED** [review]

**Comment by SREEJITH1991** [comment]
> > Hello reviewers , The issue you raised is resolved.
> > Actually we were using ECLIPSE IDE software for simulation and running purpose,so in that it was working properly because they are taking the input from the files differently.
> > .
> > but as you requested so we have changed input paths according to linux platform and now that is also working perfectly.
> > .
> > so please look into this and let us know.
> > thank you in advance.
> 
> We have checked it again. Its working fine now. The output files are updating each time we run the simulation. The only issue is the indentation problem in format_convert.cpp file. Please use 4 spaces instead of tab. If you use tab its showing different here in github. Thanks!

We have changed all the tab characters to spaces., please review

**Comment by mitalraithatha** [comment]
Hello Reviewers,
As you said about indentation issue in all 6 files + 2 new added files was not properly coming to github so we have changed all the tabs(git hub taking tab as 8 spaces that's why this was happening) to spaces manually and now in github its looking perfect.
so please check and verify for the same.
Thank you

**Pull request merged**
